API Refactoring
h1fired/nfcntu-chatbot pull request #14
Opened 2023-05-25 22:58 UTC by h1fired

- API Refactoring
- Update Tests
- Push Tests to GitHub Actions

2023-05-26 10:15 UTC, LeZenda requested changes
В загальному на порядок ліпше виглядає, але ще є декілька запитань

2023-05-26 10:15 UTC, LeZenda commented on chatbot/chatbot/settings.py
> +API_KEY = '(H+MbQeThWmYq3t6w9z$C&F)J@NcRfUj'
Ось про ці речі я й говорив, що ліпше тримати в local_settings.py файлі, котрий в гіт не попадає.

2023-05-26 10:15 UTC, LeZenda commented on chatbot/contacts/views.py
> +        return Response(contact_dict)
яка ідея цієї API, що вона повинна повертати?

2023-05-26 10:15 UTC, LeZenda commented on chatbot/users/models.py
> +    username = models.CharField(max_length=128, verbose_name='Нік користувача')
Щось не бачу міграцію по цим змінам.

2023-05-26 11:00 UTC, h1fired commented on chatbot/contacts/views.py
> +        return Response(contact_dict)
В телеграм боті буде кнопка "Важливі контакти", саме їх буде повертати API

2023-05-26 11:01 UTC, h1fired commented on chatbot/chatbot/settings.py
> +API_KEY = '(H+MbQeThWmYq3t6w9z$C&F)J@NcRfUj'
Це тестові ключі, вони потрібні для тестів в GitHub Actions.

2023-05-26 11:02 UTC, h1fired commented on chatbot/users/models.py
> +    username = models.CharField(max_length=128, verbose_name='Нік користувача')
Зрозумів, виправлю

2023-05-26 11:17 UTC, LeZenda commented on chatbot/chatbot/settings.py
> +API_KEY = '(H+MbQeThWmYq3t6w9z$C&F)J@NcRfUj'
розумію. поки нехай так буде, але потім, як буде час поглянь сюди
https://docs.github.com/en/rest/actions/secrets?apiVersion=2022-11-28
В інтернеті для будь якої ситуації, завжди є рішення, щоб секретні ключі не скидати в репозиторії, будь вони публічні чи приватні.

2023-05-26 15:32 UTC, h1fired commented on chatbot/chatbot/settings.py
> +API_KEY = '(H+MbQeThWmYq3t6w9z$C&F)J@NcRfUj'
Я переніс ключі в Action Secrets репозиторію, тепер все працює анонімно (надіюсь)

2023-05-26 15:32 UTC, h1fired commented on chatbot/users/models.py
> +    username = models.CharField(max_length=128, verbose_name='Нік користувача')
Міграцію виправив

2023-05-27 18:16 UTC, LeZenda approved these changes
ще питання залишилось по тій АПІ, але поки що можна мерджити, щоб не блочити роботу.

2023-05-27 18:16 UTC, LeZenda commented on chatbot/users/models.py
> +    username = models.CharField(max_length=128, verbose_name='Нік користувача')
І оскільки тести пройшли зеленими при відсутніх міграціях, значить тести не все покривають, необхідно добавити тести котрі б перевіряли "unique constrains"

2023-05-27 18:16 UTC, LeZenda commented on chatbot/contacts/views.py
> +        return Response(contact_dict)
мені ось це не зрозуміло
contacts = list(Contact.objects.all().values())

і ось це contact_dict[contact['group']].append({
                'name': contact['name'],
                'contact': contact['contact']
            })
            
 виглядає як те, що варто було б перекинути в серіалізатор. але якщо чесно я не до кінця розумію яка ціль цих дій :)

2023-05-27 18:33 UTC, merged